<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ltube_ftopicupdate"
 *
 * Auto generated by Extension Builder 2015-02-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'LMS3 Finished Course Update',
	'description' => 'LMS3 Finished Course Update',
	'category' => 'plugin',
	'author' => 'Nirmalya Mondal',
	'author_email' => 'nmondal@learntube.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '6.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);