<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ltube_wegaccordion"
 *
 * Auto generated by Extension Builder 2014-05-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Wegweiser Accordion',
	'description' => 'Simple Accordion for Wegweiser',
	'category' => 'plugin',
	'author' => 'Nirmalya Mondal',
	'author_email' => 'typo3india@gmail.com',
	'author_company' => 'Learntube',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
?>