<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "learntube_pdfcertificate"
 *
 * Auto generated by Extension Builder 2015-06-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'LMS3 Certificate',
	'description' => 'Learntube PDF Certificate Generate.',
	'category' => 'plugin',
	'author' => 'Nirmalya Mondal',
	'author_email' => 'nmondal@learntube.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => 1,
	'createDirs' => 'uploads/tx_learntubepdfcertificate',
	'clearCacheOnLoad' => 0,
	'version' => '7.6.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
