<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "learntube_glossary"
 *
 * Auto generated by Extension Builder 2015-10-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Learntube Glossary',
	'description' => 'Glossary system with Category.',
	'category' => 'plugin',
	'author' => 'Nirmalya Mondal',
	'author_email' => 'nmondal@learntube.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '7.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);