<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ltube_styleload"
 *
 * Auto generated by Extension Builder 2014-05-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Learntube Stylesheet Loader',
	'description' => 'Load stylesheet from page property and inheritate.',
	'category' => 'plugin',
	'author' => 'Nirmalya Mondal',
	'author_email' => 'typo3india@gmail.com',
	'author_company' => 'Learntube',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => 1,
	'createDirs' => 'uploads/tx_ltubestyleload',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 1,
	'lockType' => '',
	'version' => '6.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);