<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "videojumper"
 *
 * Auto generated by Extension Builder 2014-03-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'T3e Video Jumper',
	'description' => 'With this Extension you can add Videos as a content element that changes the page when the Video stops. It supports mobile devices and responsive design.',
	'category' => 'plugin',
	'author' => 'Marius Büscher',
	'author_email' => 'marius.buescher@gmx.de',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.6.5',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
