<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ltube_daafd"
 *
 * Auto generated by Extension Builder 2014-11-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Daa File Download Link',
	'description' => 'File with IRRE',
	'category' => 'plugin',
	'author' => 'Nirmalya Mondal',
	'author_email' => 'nmondal@learntube.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '6.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);