<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ltube_iffuserpdf"
 *
 * Auto generated by Extension Builder 2014-08-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'IFF User PDF Generate',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Nirmalya Mondal',
	'author_email' => 'nmondal@learntube.de',
	'author_company' => 'Learntube GmbH!',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '6.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);